Add PHPUnit to composer
FriendsOfSymfony/propel1-user-bundle pull request #4
Opened 2017-05-15 06:52 UTC by XWB

2017-05-15 12:02 UTC, stof requested changes

2017-05-15 12:02 UTC, stof commented on composer.json
> +        "phpunit/phpunit": "^4.8|^5.0"
use `^4.8.35 || ^5.7` instead, so that we enforce having a version containing the forward compatibility layer.

and you have not updated Travis to use this version of PHPUnit.

2017-05-15 12:02 UTC, stof commented on composer.json
> +        "phpunit/phpunit": "^4.8|^5.0"
Btw, we should probably also add the symfony/phpunit-bridge as a dev requirement to catch deprecation warnings

2017-05-16 07:35 UTC, XWB commented
@stof Done.

2017-05-19 13:40 UTC, XWB commented
@stof Can you have one final look before I merge?

2017-05-19 14:12 UTC, stof commented on composer.json
> +        "symfony/phpunit-bridge": "^2.7|^3.0"
I would just use `^3.2`, as the 3.2 version of this bridge still supports PHP 5.3 (I would even say 3.3 if it was already stable, but it is not the case yet).

2017-05-22 11:35 UTC, merged